# Generated by Django 5.2 on 2025-04-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='books/'),
            preserve_default=False,
        ),
    ]
